version: '3.8'

services:
  postgres:
    image: timescale/timescaledb-ha:pg16
    container_name: postgres_timescaledb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jessicadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/home/postgres/pgdata/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jessica_network
    restart: always

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    environment:
      CB_ADMIN_NAME: cbadmin
      CB_ADMIN_PASSWORD: password
    ports:
      - "8080:8978"
    networks:
      - jessica_network
    restart: always

  data_fetch:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    container_name: data_fetch
    volumes:
      - ./scripts:/app
    networks:
      - jessica_network
    depends_on:
      - postgres

networks:
  jessica_network:

volumes:
  postgres_data:
